'use client';
import { FormEvent, useState } from 'react';

type Props = { hotels: { id: string; name: string }[]; roomTypes: { id: string; name: string }[]; offers: { id: string; name: string; discountType: string; discountValue: number; target: string }[] };
export default function OffersManager({ hotels, roomTypes, offers: initialOffers }: Props) {
  const [offers, setOffers] = useState(initialOffers); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const response = await fetch('/api/staff/offers', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(Object.fromEntries(new FormData(form))) }); const payload = await response.json(); if (!response.ok) { setError(payload.error); return; } setOffers([{ ...payload.offer, target: payload.offer.roomTypeId || payload.offer.hotelId ? 'Targeted' : 'All branches' }, ...offers]); setMessage('Offer created.'); form.reset(); }
  return <main style={{ maxWidth: 900, margin: '4rem auto', padding: '0 1rem' }}><h1>Offers and promotions</h1><p>Active offers apply to eligible bookings before branch charges.</p><form onSubmit={submit} style={{ display: 'grid', gap: 8 }}><input name="name" placeholder="Offer name" required /><input name="description" placeholder="Description" /><select name="discountType" defaultValue="PERCENTAGE"><option value="PERCENTAGE">Percentage</option><option value="FIXED">Fixed amount in kobo</option></select><input name="discountValue" type="number" min="1" placeholder="Discount value" required /><label>Starts<input name="startsAt" type="datetime-local" required /></label><label>Ends<input name="endsAt" type="datetime-local" required /></label><select name="hotelId" defaultValue=""><option value="">All branches</option>{hotels.map(h => <option key={h.id} value={h.id}>{h.name}</option>)}</select><select name="roomTypeId" defaultValue=""><option value="">All room types</option>{roomTypes.map(r => <option key={r.id} value={r.id}>{r.name}</option>)}</select><button type="submit">Create offer</button>{message ? <p style={{ color: 'green' }}>{message}</p> : null}{error ? <p style={{ color: 'crimson' }}>{error}</p> : null}</form><h2>Existing offers</h2><ul>{offers.map(o => <li key={o.id}>{o.name} · {o.discountType === 'PERCENTAGE' ? `${o.discountValue}%` : `₦${(o.discountValue / 100).toLocaleString('en-NG')}`} · {o.target}</li>)}</ul><a href="/staff">Back to dashboard</a></main>;
}
