services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ephoenix
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ephoenix-postgres:/var/lib/postgresql/data

volumes:
  ephoenix-postgres: