import './globals.css';
import Image from 'next/image';
import Link from 'next/link';
import { Providers } from './providers';
import { AuthControls } from '../components/AuthControls';
import NavigationProgress from '../components/NavigationProgress';

export const metadata = { title: 'EPhoenix Hotels & Tourism', description: 'Three GRA addresses. One standard of stay.' };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return <html lang="en"><body id="top"><Providers><NavigationProgress /><header className="site-header"><Link href="/" className="brand"><Image src="/ephoenix-new-logo.png" width={48} height={48} alt="EPhoenix crest" /><span><b>EPhoenix</b><small>Hotels & Tourism</small></span></Link><nav><Link href="/rooms">Rooms</Link><Link href="/gallery">Gallery</Link><Link href="/locations">Locations</Link><Link href="/review">Review your stay</Link>  <Link href="/cancel">Cancel booking</Link><Link href="/cart">Cart</Link><AuthControls /><Link className="button button-gold" href="/#availability-title">Book Now</Link></nav></header>{children}<Link className="floating-book" href="/#availability-title">Book Now</Link><footer><div className="footer-grid"><div className="footer-brand"><div><span className="footer-mark">E</span><strong>EPhoenix Hotels & Tourism</strong></div><p>Three GRA addresses. One warm welcome, wherever your stay takes you.</p><Link className="footer-cta" href="/#availability-title">Plan your stay <span>→</span></Link><div className="footer-socials" aria-label="Social media"><h3>Follow us</h3><div className="social-icons"><span className="social-icon" aria-label="Facebook">f</span><span className="social-icon" aria-label="Instagram">◎</span><span className="social-icon" aria-label="TikTok">♪</span><span className="social-icon" aria-label="WhatsApp">◔</span></div></div></div><div><h3>Quick links</h3><Link href="/rooms">Rooms & suites</Link><Link href="/gallery">Gallery</Link><Link href="/locations">Our locations</Link><Link href="/cancel">Cancel booking</Link><Link href="/login">Guest login</Link><Link href="/register">Create an account</Link></div><div><h3>Visit EPhoenix</h3>{[['Main','45 Aderemi Adeleye Street, GRA, Ilorin','07077014444'],['Annex I','6 Umar Audi Road, Tanke Junction, GRA, Ilorin','08062267110'],['Annex II','13 Reservation Road, Flower Garden, GRA, Ilorin','09084878587']].map(([name,address,phone])=><div className="footer-contact" key={name}><strong>📍 {name}</strong><span>{address}</span><a href={`tel:${phone}`}>☎ {phone}</a></div>)}</div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} EPhoenix Hotels & Tourism</span><Link href="#top">Back to top ↑</Link></div></footer></Providers></body></html>;
}
