'use client';

import { FormEvent, useState } from 'react';

type Report = { occupancy: { branches: { branch: string; name: string; totalRooms: number; bookedRooms: number }[]; combined: { totalRooms: number; bookedRooms: number } }; revenue: { branches: { branch: string; name: string; grossRevenueKobo: number; refundedKobo: number; netRevenueKobo: number }[]; roomTypes: { branchName: string; roomType: string; grossRevenueKobo: number; refundedKobo: number; netRevenueKobo: number }[]; grossRevenueKobo: number; refundedKobo: number; netRevenueKobo: number; note: string }; statusBreakdown: { status: string; count: number }[] };
const money = (kobo: number) => `₦${(kobo / 100).toLocaleString('en-NG', { minimumFractionDigits: 2 })}`;

export default function ReportsDashboard() {
  const today = new Date().toISOString().slice(0, 10);
  const [start, setStart] = useState(today); const [end, setEnd] = useState(today); const [branch, setBranch] = useState('all'); const [report, setReport] = useState<Report | null>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function load(event?: FormEvent) { event?.preventDefault(); setLoading(true); setError(''); const response = await fetch(`/api/staff/reports?start=${start}&end=${end}&branch=${branch}`); const payload = await response.json(); if (!response.ok) setError(payload.error || 'Unable to load reports.'); else setReport(payload); setLoading(false); }
  return <main style={{ maxWidth: 1100, margin: '4rem auto', padding: '0 1rem' }}><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', flexWrap: 'wrap', gap: 16 }}><div><h1>Reports</h1><p>Admin-only occupancy, revenue, and booking status reports.</p></div><a href="/staff">Operations dashboard</a></div><form onSubmit={load} style={{ display: 'flex', gap: 8, flexWrap: 'wrap', margin: '2rem 0' }}><label>From<input type="date" value={start} onChange={event => setStart(event.target.value)} required /></label><label>To<input type="date" value={end} onChange={event => setEnd(event.target.value)} required /></label><label>Branch<select value={branch} onChange={event => setBranch(event.target.value)}><option value="all">All branches</option><option value="main">Main</option><option value="annex-i">Annex I</option><option value="annex-ii">Annex II</option></select></label><button type="submit" disabled={loading}>{loading ? 'Loading...' : 'Run reports'}</button></form>{error ? <p style={{ color: 'crimson' }}>{error}</p> : null}{report ? <><section><h2>Occupancy</h2><p>Combined: {report.occupancy.combined.bookedRooms} booked rooms of {report.occupancy.combined.totalRooms} total</p><table><thead><tr><th>Branch</th><th>Booked rooms</th><th>Total rooms</th></tr></thead><tbody>{report.occupancy.branches.map(item => <tr key={item.branch}><td>{item.name}</td><td>{item.bookedRooms}</td><td>{item.totalRooms}</td></tr>)}</tbody></table></section><section><h2>Revenue</h2><p>Gross: {money(report.revenue.grossRevenueKobo)} · Refunded: {money(report.revenue.refundedKobo)} · Net: {money(report.revenue.netRevenueKobo)}</p><p className="muted">{report.revenue.note}</p><table><thead><tr><th>Branch</th><th>Gross</th><th>Refunded</th><th>Net</th></tr></thead><tbody>{report.revenue.branches.map(item => <tr key={item.branch}><td>{item.name}</td><td>{money(item.grossRevenueKobo)}</td><td>{money(item.refundedKobo)}</td><td>{money(item.netRevenueKobo)}</td></tr>)}</tbody></table><h3>By room type</h3><table><thead><tr><th>Branch</th><th>Room type</th><th>Gross</th><th>Refunded</th><th>Net</th></tr></thead><tbody>{report.revenue.roomTypes.filter(item => item.grossRevenueKobo || item.refundedKobo).map(item => <tr key={item.branchName + item.roomType}><td>{item.branchName}</td><td>{item.roomType}</td><td>{money(item.grossRevenueKobo)}</td><td>{money(item.refundedKobo)}</td><td>{money(item.netRevenueKobo)}</td></tr>)}</tbody></table></section><section><h2>Booking status</h2><table><thead><tr><th>Status</th><th>Bookings</th></tr></thead><tbody>{report.statusBreakdown.filter(item => item.status !== 'completed').map(item => <tr key={item.status}><td>{item.status}</td><td>{item.count}</td></tr>)}</tbody></table></section></> : null}</main>;
}